/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 30-May-2017 20:08:43
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 67
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 67;
const int32_T B[67] = {
         33750,           0,     -158564,           0,      434741,           0,
       -958406,           0,     1857630,           0,    -3296132,           0,
       5477758,           0,    -8654236,           0,    13141304,           0,
     -19353609,           0,    27880863,           0,   -39659140,           0,
      56384887,           0,   -81653719,           0,   124845286,           0,
    -220551578,           0,   681099602,  1073741824,   681099602,           0,
    -220551578,           0,   124845286,           0,   -81653719,           0,
      56384887,           0,   -39659140,           0,    27880863,           0,
     -19353609,           0,    13141304,           0,    -8654236,           0,
       5477758,           0,    -3296132,           0,     1857630,           0,
       -958406,           0,      434741,           0,     -158564,           0,
         33750
};
