/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 30-May-2017 20:14:44
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 57
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 57;
const int32_T B[57] = {
        -50436,      -80496,      -47034,      122020,      497831,     1116512,
       1937445,     2805973,     3436158,     3429233,     2338172,     -221494,
      -4428060,   -10104534,   -16601294,   -22750245,   -26922700,   -27205572,
     -21685528,    -8803364,    12282244,    41395068,    77176656,   117108681,
     157741603,   195108686,   225265120,   244862686,   251658240,   244862686,
     225265120,   195108686,   157741603,   117108681,    77176656,    41395068,
      12282244,    -8803364,   -21685528,   -27205572,   -26922700,   -22750245,
     -16601294,   -10104534,    -4428060,     -221494,     2338172,     3429233,
       3436158,     2805973,     1937445,     1116512,      497831,      122020,
        -47034,      -80496,      -50436
};
