/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 03-Jun-2017 16:02:36
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 56
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 56;
const int32_T B[56] = {
        -45562,      -63403,       -5117,      202547,      624912,     1281635,
       2103563,     2898013,     3339562,     3002045,     1440299,    -1682081,
      -6437854,   -12487067,   -18975425,   -24521035,   -27318617,   -25368066,
     -16805629,     -287264,    24647694,    57312136,    95775756,   136981210,
     177074620,   211908918,   237639643,   251308723,   251308723,   237639643,
     211908918,   177074620,   136981210,    95775756,    57312136,    24647694,
       -287264,   -16805629,   -25368066,   -27318617,   -24521035,   -18975425,
     -12487067,    -6437854,    -1682081,     1440299,     3002045,     3339562,
       2898013,     2103563,     1281635,      624912,      202547,       -5117,
        -63403,      -45562
};
